#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# https://wiki.archlinux.org/index.php/XDG_Base_Directory_support
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_DATA_DIRS=/usr/local/share:/usr/share
export XDG_CONFIG_DIRS=/etc/xdg

# history file options
export HISTCONTROL=ignorespace:ignoredups
 
# append to history file
shopt -s histappend

# review substitution result
shopt -s histverify
 
# check window size after each command
shopt -s checkwinsize
 
# disallow messages from other users
mesg n

# vi mode in bash
set -o vi

# add $HOME/bin to path
if [[ -d "$HOME/bin" ]]; then
  export PATH="$HOME/bin:$PATH"
fi
 
# bash auto-completion
if [[ -f /etc/bash_completion ]]; then
  . /etc/bash_completion
fi

# git auto-completion
if [[ -f /usr/share/git/completion/git-completion.bash ]]; then
  . /usr/share/git/completion/git-completion.bash
fi

# prompt
GREEN="\[\033[32m\]"
BLACK="\[\033[0;39m\]"
WHITE="\[\033[33m\]"
YELLOW="\[\033[35m\]"
#export PS1="$GREEN\u$BLACK@$WHITE\h $YELLOW\W$BLACK\$ "
PROMPT_START="$YELLOW\w$BLACK"
PROMPT_END="$BLACK> "
export PROMPT_COMMAND=''
export PS1="$PROMPT_START$PROMPT_END"

# if gompt exists, replace default prompt
if ( [[ "$TERM" =~ ^xterm* ]] \
     || [[ "$TERM" =~ ^screen* ]] \
     || [[ "$TERM" =~ ^rxvt* ]] \
     || [[ "$TERM" =~ ^st* ]] ) \
   && hash gompt 2>/dev/null; then

  function _update_ps1() {
    export PS1="$(gompt -s $?)"
  }
  export PROMPT_COMMAND="_update_ps1;"
fi

# aliases
# A trailing space in VALUE causes the next word to be checked for alias substitution when the alias is expanded.
# If the last character of the alias value is a space or tab character, then the next command word following the alias is also checked for alias expansion.
alias ls='ls -ph --color=auto --group-directories-first'
alias l='ls -l'
alias ll='l -a'
alias lt='l -t'
alias llt='ll -t'
alias t='tree -phC'
alias tt='t -a'
alias vim='vim -p'
alias vi='vim'
alias v='vim'
alias vif='vi `find ./ -name \!#:1`'
alias open='xdg-open'
alias o='open'
alias oo='open .'
alias grep='grep --color=auto'
alias g='grep -ir'
alias f='find ./ -iname'
alias rebash='source ~/.bashrc'
alias sudo='sudo '
alias watch='watch '
alias gdb='LC_ALL=C gdb'
alias bd=". bd -si"
alias list-ws='for m in $(bspc query -M --names); do echo "== $m =="; bspc query -T -m $m | jq ".desktops[] | .name, .id"; done'
alias fs="stat -c \"%s bytes\""
alias mv='mv -v'
alias rm='rm -i -v'
alias cp='cp -v'
alias aurman='aurman --color always'

# find any "*name*"
function ff()
{
  obj=$1
  shift 1
  find ./ -iname "*$obj*" $*
}

# make directory with parents
function md()
{
  mkdir -p "$@" && cd "$@"
}

# default pager
export PAGER='vimpager'
export MANPAGER='vimpager'

# default editor
export EDITOR="vim"

# color in gcc/g++
export GCC_COLORS=1

# environment variable: http://pubs.opengroup.org/onlinepubs/7908799/xbd/envvar.html
export LANG="en_US.UTF-8"

# enable coredump
ulimit -H -c unlimited
ulimit -S -c unlimited

# direnv
eval "$(direnv hook bash)"

# personalize colors of ls command
# http://www.linux-sxs.org/housekeeping/lscolors.html
#eval $(dircolors ~/.dircolors)

# local bashrc
[[ -f ~/.bashrc_local ]] && . ~/.bashrc_local

# default ANSI colors
# https://github.com/chriskempson/base16-shell
BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"
