"" My vimrc!

" Faster refraw
set ttyfast

" disable vi compatibility
set nocompatible
 
" disable blinks and beeps
set noerrorbells
 
" enable mouse
if has('mouse')
  set mouse=nic " do not enable in visual mode
endif
 
" display line numbers
set nu
"set relativenumber

" Consider a file large in MB
let g:LargeFile=10
 
" define keys <backspace> and <del>
" remove: indent, eol, start
"   - 0 => none
"   - 1 => indent,eol
"   - 2 => indent,eol,start
set bs=2
 
" smart indent
set smartindent
 
" load indent and plugins depending of filetype
filetype plugin indent on
 
" syntax highlighting
syntax on

" force fileformats
set fileformats=unix
 
" display status bar
" 'set rulerformat=[...]'
set laststatus=2
set ruler
 
" display incomplete commands in status bar
set showcmd

" navigate between unsave buffers
set hidden

" command completion
set wildmode=longest,list,full
set wildmenu
 
" replace tab by spaces
set expandtab
 
" auto-indent size (+ >> and <<)
set shiftwidth=4
 
" size indent <tab> and <backspace>
set softtabstop=4
 
" size indent for <tab> without 'expandtab'
set tabstop=4
 
" loop search
set wrapscan
 
" incremental search
set incsearch
 
" enable color highlighting of search
set hlsearch

" ignore case search
set ignorecase
set smartcase

" jump to matching bracket
set showmatch
 
" disable backups (~file)
set nobackup

" underline current line
set cursorline

" scroll lines around
set scrolloff=10
set sidescrolloff=5

" refresh file if updated
set autoread

" more natural way to open split panes
set splitbelow
set splitright
 
" indent param for some filetypes
au FileType html set softtabstop=2
au FileType html set shiftwidth=2
au FileType html set tabstop=2

au FileType css set softtabstop=2
au FileType css set shiftwidth=2
au FileType css set tabstop=2

au FileType scss set softtabstop=2
au FileType scss set shiftwidth=2
au FileType scss set tabstop=2
 
au FileType xml set softtabstop=2
au FileType xml set shiftwidth=2
au FileType xml set tabstop=2
 
au FileType ant set softtabstop=2
au FileType ant set shiftwidth=2
au FileType ant set tabstop=2
 
au FileType php set softtabstop=2
au FileType php set shiftwidth=2
au FileType php set tabstop=2
 
au FileType yaml set softtabstop=2
au FileType yaml set shiftwidth=2
au FileType yaml set tabstop=2
 
au FileType javascript set softtabstop=2
au FileType javascript set shiftwidth=2
au FileType javascript set tabstop=2
 
au FileType ruby set softtabstop=2
au FileType ruby set shiftwidth=2
au FileType ruby set tabstop=2
 
au FileType python set softtabstop=2
au FileType python set shiftwidth=2
au FileType python set tabstop=2

au FileType eruby set softtabstop=2
au FileType eruby set shiftwidth=2
au FileType eruby set tabstop=2

au FileType xquery set softtabstop=2
au FileType xquery set shiftwidth=2
au FileType xquery set tabstop=2

" file templates
"autocmd BufNewFile main.cpp 0r $HOME/.vim/templates/main.cpp.tpl
"autocmd BufNewFile Makefile 0r $HOME/.vim/templates/Makefile.tpl


"Plugin 'tpope/vim-fugitive'
"Plugin 'chriskempson/base16-vim'
"Plugin 'AnsiEsc.vim'
"Plugin 'altercation/vim-colors-solarized'
"Plugin 'rust-lang/rust.vim'
"Plugin 'sheerun/vim-polyglot.git'
"Plugin 'bkad/CamelCaseMotion'



" color scheme

" number of colors
" https://github.com/chriskempson/base16-shell
"let base16colorspace="256"

" dark background
set background=dark

" theme
colorscheme base16-solarized-dark

" CamelCaseMotion
"call camelcasemotion#CreateMotionMappings('<leader>')

" Vim cheats a little to enable the mouse with xterms, and once you are
" using a different $TERM this cheat stops working. You need to tell Vim
" about your terminal's mouse support. This is done with Vim's ttymouse
" setting.
set ttymouse=xterm2

" 24-bit color support
set termguicolors
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
