#!/bin/sh

#xrdb ~/.Xresources
sxhkd -c $HOME/.config/sxhkd/sxhkdrc -m 1 &

bspc monitor -d term code web mail music other

bspc config border_width        4
bspc config window_gap          8

bspc config split_ratio         0.5
bspc config borderless_monocle  false
bspc config gapless_monocle     false

bspc config top_padding 0
bspc config -m primary top_padding 28

bspc desktop web -l monocle

bspc rule -a Thunderbird desktop=mail
bspc rule -a Spotify desktop=music
bspc rule -a Steam desktop=game state=floating
bspc rule -a firefox desktop=web
bspc rule -a Chromium desktop=game
bspc rule -a Wicd-client.py state=floating
bspc rule -a Pavucontrol state=floating

#bspc config focus_follows_pointer true
bspc config click_to_focus true

# mouse support
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#$HOME/bin/monitors-refresh
#MONITOR=$(monitors get -p) $HOME/.config/polybar/launch.sh
$HOME/.config/polybar/launch.sh
$HOME/.fehbg &

# network manager
wicd-client -t &

# https://ignorantguru.github.io/spacefm/spacefm-manual-en.html#invocation-daemonmode
spacefm -d &

# locker
light-locker &
xautolock -time 2 -locker "loginctl lock-sessions" -detectsleep

# notification system
dunst &

# clipboard manager
xfce4-clipman &
